# Site settings
course_name: Foundations of Machine Learning
course_description: "In today’s rapidly evolving world, machine learning (ML) is crucial in driving innovation across
industries. From healthcare and finance to e-commerce and autonomous systems, ML enables computers to learn from data 
and make intelligent decisions. By understanding machine learning, individuals can harness the power of data to predict 
trends, automate processes, and develop smarter applications. With the growing demand for AI-driven solutions, a strong 
foundation in ML equips professionals with cutting-edge skills essential in shaping the future of technology 
and solving real-world challenges."
course_semester: "July-Dec 2024"

baseurl: "/foml24" # the subpath of your site, e.g. /blog/
url: "http://krmopuri.github.io/" # the base hostname & protocol for your site

schoolname: "Dept. of AI, IITH"
schoolurl: "https://ai.iith.ac.in/"
#twitter_username: username 

address: |
    Department of Artificial Intelligence
    IIT Hyderabad, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
